# Uncomment the next line to define a global platform for your project
#platform :ios, 9.0'

target 'DevTool' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '4.0.1'
  pod 'Kingfisher', '~> 4.9.0'
  pod 'Toast-Swift', '5.0.0'

end
